# Generated by Django 2.1.5 on 2019-02-05 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20170415_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='board',
            field=models.ForeignKey(on_delete=True, to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=True, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(null=True, on_delete=True, to='boards.State'),
        ),
    ]
